- name: Setup local server by installing required services and tools
  hosts: localhost  
  become: true    

  roles:
    - apt-get-services
    - enable-other-services
    - setup-openvas
    - setup-tools
    - add-remote-users
