---
# tasks file for apt-get-services

- name: Update apt packages
  become: true
  apt:
    upgrade: yes
    dpkg_options: 'force-confold,force-confdef'
    force: yes

- name: Upgrade all packages to the latest version
  become: true
  apt:
    name: "*"
    state: latest
    dpkg_options: 'force-confold,force-confdef'
    force: yes

- name: Update all packages to the latest version - dist
  become: true
  apt:
    upgrade: dist
    dpkg_options: 'force-confold,force-confdef'
    force: yes

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  become: true  
  vars:
    packages:
      - tcpdump
      - screen
      - tmux
      - htop
      - libtool
      - autotools-dev
      - pkg-config
      - libssl-dev
      - python-pip
      - autoconf
      - automake
      - unzip
      - p7zip-full
      - sudo
      - xauth
      - python3
      - python3-dev
      - python3-pip
      - autossh
      - mailutils
      - iptables-persistent
      - socat
      - tor
      - obfs4proxy
      - uudeview
      - dirb
      - wget
      - curl
      - jq
      - ftp
      - zmap
      - gobuster
      - openvas
      - openvas-cli
      - openvas-nasl
      - greenbone-security-assistant
      - gnupg
      - apt-transport-https
      - golang
      - hydra
      - nmap
      - masscan
      - nfs-common
      - libffi-dev
      - python-dev
      - build-essential
      - iperf
      - wpscan
      - python-virtualenv
      - python3-virtualenv
      - responder
      - ansible
      #- shred
      - libolm-dev
      #- geoip
      - tor-geoipdb
      - python-geoip
      - python3-geoip
      - geoip-bin
      - geoip-database
      - geoip-database-extra
      - arachni
      - iodine
      - proxychains
      - ncat
      - mtr
      - git
      - netcat
      - pwgen
      - mutt
      - mitmproxy
      - maven
      - libkrb5-dev  

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: true      