---
# tasks file for apt-get-services

- name: Update apt packages
  apt:
    upgrade: yes
    dpkg_options: 'force-confold,force-confdef'
    force: yes

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    dpkg_options: 'force-confold,force-confdef'
    force_apt_get: yes
    force: yes

- name: Update all packages to the latest version - dist
  apt:
    upgrade: dist
    dpkg_options: 'force-confold,force-confdef'
    force: yes

- name: Install a list of packages
  apt:
    name: "{{ packages }}"

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes