---

- name: Remove crackmapexec package
  apt:
    name: crackmapexec
    state: absent 

- pip:
    name: pipenv
    extra_args: --user 

- name: Git clone CrackMapExec repository
  git:
    repo: 'https://github.com/byt3bl33d3r/CrackMapExec.git'
    dest: "{{ tool_dir }}"
    clone: yes  
    recursive: yes

