---
# tasks file for setup-tools

- name: include vars
  include_vars: "{{ playbook_dir }}/global_vars.yaml"

- name: Creates directory
  file:
    path: "{{ tool_dir }}"
    state: directory

- include: 
    # - install-powershell-empire.yml
    # - install-crackmapexec.yml
    # - install-siet.yml
    - install-emailharvester.yml