---
# tasks file for add-users

- name: Clone private git repository
  git:
    repo: "{{ private_git_repo }}"
    key_file: "{{ git_ssh_key_location }}"
    dest: "{{ repo_directory }}"

- name: Include user management playbook
  include: "{{ repo_directory }}/{{ user_playbook }}"      