---

- name: Git clone merlin-server repository
  git:
    repo: "{{ git_repo_merlin }}"
    dest: "{{ go_path }}/src/github.com/Ne0nd0g/merlin"
    clone: yes

- name: Install merlin-server
  make:
    chdir: "{{ go_path }}/src/github.com/Ne0nd0g/merlin"
    target: server-linux
  environment:
    GOPATH: "{{ go_path }}"      