---

- name: Git clone powershell empire repository
  git:
    repo: "{{ git_repo_empire }}"
    dest: "{{ tool_dir }}/Empire"
    clone: yes

- name: Create required key
  command: openssl rand -base64 32 
  register: staging_key

- name: Install powershell empire
  command: bash install.sh 
  args:
    chdir: "{{ tool_dir }}/Empire/setup"
  environment:
    STAGING_KEY: "{{ staging_key.stdout }}"