---

- name: Install matrix client
  pip:
    name: matrix_client

- name: Git clone python-matrix-bot-api repository
  git:
    repo: "{{ git_repo_python_matrix_bot_api }}"
    dest: "{{ tool_dir }}/python-matrix-bot-api"
    clone: yes

- name: Install matrix-python-sdk for encryption
  pip:
    name: "{{ git_repo_python_matrix_sdk }}"
    executable: pip3
    extra_args: --process-dependency-links