---

- name: Git clone macropack repository
  git:
    repo: "{{ git_repo_macro_pack }}"
    dest: "{{ tool_dir }}/macro_pack"
    clone: yes

- name: Install requirements
  pip: 
    requirements: "{{ tool_dir }}/macro_pack/requirements.txt"
    virtualenv: "{{ tool_dir }}/macro_pack"
    virtualenv_python: "{{ python_3_version }}"    