---

- name: Git clone cracke-dit repository
  git:
    repo: "{{ git_repo_cracke_dit }}"
    dest: "{{ tool_dir }}/cracke-dit"
    clone: yes

- name: Install requirements
  pip: 
    requirements: "{{ tool_dir }}/cracke-dit/requirements.txt"
    virtualenv: "{{ tool_dir }}/cracke-dit"
    virtualenv_python: "{{ python_2_version }}"    