---

- name: Git clone spoofcheck repository
  git:
    repo: "{{ git_repo_spoofcheck }}"
    dest: "{{ tool_dir }}/spoofcheck"
    clone: yes

- name: Install requirements
  pip: 
    requirements: "{{ tool_dir }}/spoofcheck/requirements.txt"
    virtualenv: "{{ tool_dir }}/spoofcheck"
    virtualenv_python: "{{ python_2_version }}"    