---

- name: Git clone ews-crack repository
  git:
    repo: 'https://github.com/mikesiegel/ews-crack.git'
    dest: "{{ tool_dir }}/ews-crack"
    clone: yes

- name: Install requirements
  pip: 
    requirements: "{{ tool_dir }}/ews-crack/requirements.txt"
    virtualenv: "{{ tool_dir }}/ews-crack"
    virtualenv_python: "{{ python_2_version }}"    