---

- name: Remove crackmapexec package
  apt:
    name: crackmapexec
    state: absent 

- pip:
    name: pipenv
    extra_args: --user 

- name: Git clone CrackMapExec repository
  git:
    repo: 'https://github.com/byt3bl33d3r/CrackMapExec.git'
    dest: "{{ tool_dir }}/CrackMapExec"
    clone: yes  
    recursive: yes

- name: pip env install and run setup
  command: "{{ item }}"
  args:
    chdir: "{{ tool_dir }}/CrackMapExec"
  environment:
    PATH: "{{ ansible_env.PATH }}:/root/.local/bin"
  with_items:
    - pipenv install
    - pipenv run python setup.py install