---

- name: Git clone EmailHarvester repository
  git:
    repo: "{{ git_repo_emailharvester }}"
    dest: "{{ tool_dir }}/EmailHarvester"
    clone: yes

- name: Install requirements
  pip: 
    requirements: "{{ tool_dir }}/EmailHarvester/requirements.txt"
    virtualenv: "{{ tool_dir }}/EmailHarvester"
    virtualenv_python: "{{ python_3_version }}"    